import React from 'react';
import { useNavigate } from 'react-router-dom';
import '../../styles/dashboard/Recommendation.css';

export default function Recommendations({ userId }) {
  const navigate = useNavigate();

  // Mock data - you'll replace this with ML-powered recommendations later
  const masteryGaps = [
    {
      id: 1,
      topic: 'While Loops',
      mastery: 45,
      status: 'needs-review',
      lessonId: 3,
    },
    {
      id: 2,
      topic: 'Functions',
      mastery: 68,
      status: 'practice-recommended',
      lessonId: 4,
    },
  ];

  const suggestions = [
    {
      id: 1,
      type: 'peer-comparison',
      text: 'Ahead of 60% of peers in "Control Flow"',
      icon: '📈',
    },
    {
      id: 2,
      type: 'ready-for',
      text: 'Ready for Advanced Functions',
      icon: '✨',
    },
    {
      id: 3,
      type: 'trending',
      text: 'Object-Oriented Programming is trending',
      icon: '🔥',
    },
  ];

  const getStatusColor = (status) => {
    if (status === 'needs-review') return 'status-red';
    if (status === 'practice-recommended') return 'status-orange';
    return 'status-green';
  };

  const getStatusText = (mastery) => {
    if (mastery < 60) return 'Needs Review';
    if (mastery < 75) return 'Practice Recommended';
    return 'Good Progress';
  };

  return (
    <div className="recommendations">
      <h2 className="section-title">💡 Personalized Recommendations</h2>
      <p className="section-subtitle">
        Based on your learning patterns and performance
      </p>

      {/* Mastery Gaps */}
      {masteryGaps.length > 0 && (
        <div className="recommendations-section">
          <h3 className="subsection-title">Mastery Gaps</h3>
          <div className="mastery-gaps">
            {masteryGaps.map((gap) => (
              <div key={gap.id} className="mastery-gap-card">
                <div className="gap-header">
                  <div className="gap-info">
                    <h4 className="gap-topic">{gap.topic}</h4>
                    <span className={`gap-status ${getStatusColor(gap.status)}`}>
                      {getStatusText(gap.mastery)}
                    </span>
                  </div>
                  <div className="gap-mastery">
                    <div className="mastery-circle">
                      <svg width="60" height="60" viewBox="0 0 60 60">
                        <circle
                          cx="30"
                          cy="30"
                          r="25"
                          fill="none"
                          stroke="#e2e8f0"
                          strokeWidth="5"
                        />
                        <circle
                          cx="30"
                          cy="30"
                          r="25"
                          fill="none"
                          stroke={gap.mastery < 60 ? '#f56565' : '#ed8936'}
                          strokeWidth="5"
                          strokeDasharray={`${(gap.mastery / 100) * 157} 157`}
                          strokeLinecap="round"
                          transform="rotate(-90 30 30)"
                        />
                        <text
                          x="30"
                          y="30"
                          textAnchor="middle"
                          dy=".3em"
                          fontSize="14"
                          fontWeight="700"
                          fill="#1a202c"
                        >
                          {gap.mastery}%
                        </text>
                      </svg>
                    </div>
                  </div>
                </div>
                <button 
                  className="btn-review"
                  onClick={() => navigate(`/lessons/${gap.lessonId}`)}
                >
                  Review Topic →
                </button>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Suggested Topics */}
      <div className="recommendations-section">
        <h3 className="subsection-title">Suggested Next Topics</h3>
        <div className="suggestions-list">
          {suggestions.map((suggestion) => (
            <div key={suggestion.id} className="suggestion-item">
              <span className="suggestion-icon">{suggestion.icon}</span>
              <span className="suggestion-text">{suggestion.text}</span>
            </div>
          ))}
        </div>
      </div>

      {/* AI Insight Badge */}
      <div className="ai-insight">
        <span className="ai-badge">🤖 AI-Powered Insights</span>
        <p className="ai-text">
          These recommendations are generated by analyzing your learning patterns,
          quiz performance, and time spent on each topic.
        </p>
      </div>
    </div>
  );
}